### ISSUE TITLE
Weird ALE Signcolumn sign

### ISSUE THREAD

**Issue by 6cdh** [monsonjeremy/onedark.nvim#1]
[ALE](https://github.com/dense-analysis/ale) Signcolumn Sign is weird:

![Screenshot from 2021-05-24 12-21-21](https://user-images.githubusercontent.com/39000776/119295924-936f8480-bc8a-11eb-90f8-e290dc541475.png)

I expect this (with [one-nvim](https://github.com/Th3Whit3Wolf/one-nvim) colorscheme)

![Screenshot from 2021-05-24 12-24-51](https://user-images.githubusercontent.com/39000776/119296188-11cc2680-bc8b-11eb-9785-21fd3fe8a7fa.png)

My [init.lua](https://github.com/6cdh/dotfiles/blob/53e4c4fd52e8ced1332fdba779d65823ead71375/nvim/.config/nvim/init.lua) and [ALE config](https://github.com/6cdh/dotfiles/blob/53e4c4fd52e8ced1332fdba779d65823ead71375/nvim/.config/nvim/lua/diagnostic.lua)

**Comment by monsonjeremy** [comment]
I can take a look today, I don't have ALE so I'll rely on you to verify my fix has worked 😄 

I think I just need to support the ALE highlights and it'll work!

**Comment by 6cdh** [comment]
Thanks :)

**Comment by monsonjeremy** [comment]
Okay I've added the two ALE highlight groups that were present in the repo you linked. Should work now, let me know if it doesn't.

```lua
    -- ALE
    ALEWarningSign = { fg = c.yellow },
    ALEErrorSign   = { fg = c.red },
```

**Comment by 6cdh** [comment]
Fixed. Thanks for your work.

**Comment by monsonjeremy** [comment]
@6cdh My pleasure, thanks for using my theme! Let me know if you find anything else 😀

**Comment by 6cdh** [comment]
Really enjoy it!
