### ISSUE TITLE
transparency only on buffers and telescope

### ISSUE THREAD

**Issue by aserowy** [monsonjeremy/onedark.nvim#2]
First things first: Nice theme! Thx for your work.

Im trying to go for transparency, but all non buffer windows (except telescope and the current active buffer) still have background. Is this a feature or a bug? :D

![image](https://user-images.githubusercontent.com/8199164/119366964-c9742f00-bcb1-11eb-93d3-62050b23b00f.png)

**Comment by 6cdh** [comment]
It's a feature. See `onedark_sidebars` and `onedark_dark_sidebar` in README.md.

**Comment by aserowy** [comment]
But even when I unset these, their background stay (at a lighter color).

**Comment by monsonjeremy** [comment]
This is absolutely a bug, I likely missed overriding the sidebar/terminal backgrounds to be transparent. I'll take a look later today!

**Comment by 6cdh** [comment]
Well, unset `onedark_dark_sidebar` in packer doesn't work:

```lua
use {
    'monsonjeremy/onedark.nvim',
    config = function() vim.g.onedark_dark_sidebar = false end
}
```

But unset it outside packer works:

```lua
packer.startup(function()
    use {'monsonjeremy/onedark.nvim'}
end)

// ...

vim.g.onedark_dark_sidebar = false
```

I don't know why. Maybe a bug.

By the way, this plugin is brilliant!

**Comment by monsonjeremy** [comment]
> Well, unset `onedark_dark_sidebar` in packer doesn't work:
> 
> ```lua
> use {
>     'monsonjeremy/onedark.nvim',
>     config = function() vim.g.onedark_dark_sidebar = false end
> }
> ```
> 
> But unset it outside packer works:
> 
> ```lua
> packer.startup(function()
>     use {'monsonjeremy/onedark.nvim'}
> end)
> 
> ...
> 
> vim.g.onedark_dark_sidebar = false
> ```
> 
> I don't know why. Maybe a bug.
> 
> By the way, this plugin is brilliant!

I think this may depend on when you call `colorscheme onedark`. Are you setting that option before or after?

**Comment by monsonjeremy** [comment]
I believe i've fixed the transparency issue, if you don't mind pulling down the latest and letting me know. It looked good on my local but I may have missed some stuff.

**Comment by aserowy** [comment]
Hi,

thx for this good start into the week :D
One small add to the issue: If onedark_hide_inactive_statusline is set while transparent will not draw a thin line.

![image](https://user-images.githubusercontent.com/8199164/119442940-03344c80-bd29-11eb-8e76-0ede6bf1f6a4.png)

**Comment by monsonjeremy** [comment]
> Hi,
> 
> 
> 
> thx for this good start into the week :D
> 
> One small add to the issue: If onedark_hide_inactive_statusline is set while transparent will not draw a thin line.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/8199164/119442940-03344c80-bd29-11eb-8e76-0ede6bf1f6a4.png)
> 
> 

Nice find, it should also be transparent on the background. I'll fix that as well. 

As for the thin line, i've had issues with getting the hidden bar to work when using Packer. If I reload my config it works as expected, so I think there's something that's running async an overwriting it. I'll take a look another night.

**Comment by 6cdh** [comment]
@monsonjeremy 
It works whether before or after `colorscheme onedark`. Just does not work in the packer config.

I put them into packer. Now everything works:

```lua
use {
    'monsonjeremy/onedark.nvim',
    config = function()
        vim.g.onedark_dark_sidebar = false
        vim.api.nvim_command [[colorscheme onedark]]
    end
}
```

**Comment by monsonjeremy** [comment]
@aserowy That's interesting I'm not sure where that red line would come from. Definitely can't be from git since it's in the end of buffer gutter. I can take a look in the next couple days.

**Comment by aserowy** [comment]
Sry for the confusion. I have drawn it to show the end of buffer signs 🤣

**Comment by monsonjeremy** [comment]
Ahh i see the issue now @aserowy. This one is a little tricky. The way the transparency works for the background is that the `guibg` is set to `NONE` when transparency option is set. Doing this for the `EndOfBuffer` highlight group just makes it show up white. 

I'll take another look and see if I can figure out a workaround.

**Comment by aserowy** [comment]
These signs are unimportant. Don't waste your time on this! 😅

**Comment by monsonjeremy** [comment]
@aserowy I'm going to close the issue, since I don't think there is a good way to resolve the highlights for those. My recommendation is just to hide them by setting this in your config
`set fillchars=eob:\ ,`
