### ISSUE TITLE
Wrong colors when programming in Rust

### ISSUE THREAD

**Issue by jrmoulton** [monsonjeremy/onedark.nvim#20]
When programming in rust keywords such as ```fn```, and ```impl``` that should be purple show up as a teal color when in other onedark themes they are purple. But keywords such as ```for```, ```in```, and ```match``` are correctly colored. 
I don't have this issue when programming in python though.

**Comment by jrmoulton** [comment]
It might actually just be how you want your theme styled I guess but I think this
https://github.com/monsonjeremy/onedark.nvim/blob/b40cc9fb1e1d7855bc4687f1acd2e1f3f2fc66de/lua/onedark/theme.lua#L99
would usually be purple. I forked it and changed it and now it is how I would expect it to be.

**Comment by monsonjeremy** [comment]
Good find, I don't use Rust much so I never noticed. Let me add your suggested changes and see how it looks for JS/TS.
