### ISSUE TITLE
Configure plugin in lua using `require('onedark').setup({})`

### ISSUE THREAD

**Issue by yochem** [monsonjeremy/onedark.nvim#5]
First of all, thank you for the plugin! It works very well.

I see a trend of lua plugins for nvim having the following for configuration:

```lua
require('hlslens').setup({calm_down = true})
```

This is for example the case with hlslens, hardline and others. Would it be a possibility to also allow this type of setup? It makes the `vim.g` space less cluttered, easy to find the configuration for a specific plugin and makes it easier to clean up the config files.

Example  from the readme converted:
```lua
require('onedark').setup({
    italic_functions = true,
    sidebars = { "qf", "vista_kind", "terminal", "packer" },

    -- Change the "hint" color to the "orange" color, and make the "error" color bright red
    colors = { hint = "orange", error = "#ff0000" }
})
```

Let me know what you think :)

**Comment by monsonjeremy** [comment]
@yochem This is incoming, hoping to have it out later today! Thanks to @ful1e5 for doing it on his version :D

**Comment by monsonjeremy** [comment]
Done! sorry for the delay!
