### ISSUE TITLE
[Feature Request] Color scheme support for barbar and galaxyline

### ISSUE THREAD

**Issue by luong-komorebi** [monsonjeremy/onedark.nvim#8]
Galaxyline: https://github.com/glepnir/galaxyline.nvim
Barbar: https://github.com/romgrk/barbar.nvim 

Both are very popular plugins. Thank you for such an amazing color scheme

**Comment by monsonjeremy** [comment]
I'll take a look at this sometime during this week!

**Comment by monsonjeremy** [comment]
@luong-komorebi Thanks to @ful1e5 there is now `barbar` support. I can take a look at `galaxyline` when I have some time. You can also try setting color overrides until I get a chance to do it myself!

**Comment by luong-komorebi** [comment]
Thank you so much. Yes I did notice the commits and I think it s good to close this issue. Looking forward to see `barbar` and `galaxyline` being reference in the readme. Great work!
